### ISSUE TITLE
view loading problem

### ISSUE THREAD

**Issue by Mattwig** [Mattwig/ITC298-final#1]
Problem loading the view after adding ingredients in index.js line 75 "cannot read property 'name' of undefined"  @thomaswilburn

**Comment by thomaswilburn** [comment]
You can't request these values async and then try to use them outside the callback--they don't exist yet. This is a great chance to use `async` to get the data but only act when they are both available:

```
async.parallel([
  function(callback) { model.loadIngredients(callback) },
  function(callback){ model.loadRecipe(callback) }
], function() {
  //both have been run now
})
```
